all: bubblesort quicksort

bubblesort: bubblesort.cpp
	g++ -std=c++11 -I/opt/local/include -L/opt/local/lib -lGL -lglut -lavl bubblesort.cpp -o bubblesort

quicksort: quicksort.cpp
	g++ -std=c++11 -I/opt/local/include -L/opt/local/lib -lGL -lglut -lavl quicksort.cpp -o quicksort
